// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestDocumentService.Data.Context;

#nullable disable

namespace TestDocumentService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FirmTestDocument", b =>
                {
                    b.Property<int>("FirmsId")
                        .HasColumnType("int");

                    b.Property<int>("TestDocumentsId")
                        .HasColumnType("int");

                    b.HasKey("FirmsId", "TestDocumentsId");

                    b.HasIndex("TestDocumentsId");

                    b.ToTable("FirmTestDocument");
                });

            modelBuilder.Entity("ParticipantTestDocument", b =>
                {
                    b.Property<int>("ParticipantsId")
                        .HasColumnType("int");

                    b.Property<int>("TestDocumentsId")
                        .HasColumnType("int");

                    b.HasKey("ParticipantsId", "TestDocumentsId");

                    b.HasIndex("TestDocumentsId");

                    b.ToTable("ParticipantTestDocument");
                });

            modelBuilder.Entity("TestDocumentService.Models.DefinitionAndAbbrevation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbrevation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Definition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TestDocumentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TestDocumentId");

                    b.ToTable("DefinitionAndAbbrevation");
                });

            modelBuilder.Entity("TestDocumentService.Models.Firm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("FAT")
                        .HasColumnType("bit");

                    b.Property<string>("FullAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IAT")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OAT")
                        .HasColumnType("bit");

                    b.Property<bool>("SAT")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Firm");
                });

            modelBuilder.Entity("TestDocumentService.Models.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FirmId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Signature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FirmId");

                    b.ToTable("Participant");
                });

            modelBuilder.Entity("TestDocumentService.Models.Punch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PunchNumber")
                        .HasColumnType("int");

                    b.Property<int>("TestDocumentId")
                        .HasColumnType("int");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TestDocumentId");

                    b.HasIndex("TestId");

                    b.ToTable("Punch");
                });

            modelBuilder.Entity("TestDocumentService.Models.Revision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChapterAffected")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PageAffected")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TestDocumentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TestDocumentId");

                    b.ToTable("Revision");
                });

            modelBuilder.Entity("TestDocumentService.Models.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FATInitials")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IATInitials")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OATInitials")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SATInitials")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TestDocumentId")
                        .HasColumnType("int");

                    b.Property<string>("TestProcedure")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TestDocumentId");

                    b.ToTable("Test");
                });

            modelBuilder.Entity("TestDocumentService.Models.TestDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentSupplied")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Introduction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TestDocuments");
                });

            modelBuilder.Entity("FirmTestDocument", b =>
                {
                    b.HasOne("TestDocumentService.Models.Firm", null)
                        .WithMany()
                        .HasForeignKey("FirmsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestDocumentService.Models.TestDocument", null)
                        .WithMany()
                        .HasForeignKey("TestDocumentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ParticipantTestDocument", b =>
                {
                    b.HasOne("TestDocumentService.Models.Participant", null)
                        .WithMany()
                        .HasForeignKey("ParticipantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestDocumentService.Models.TestDocument", null)
                        .WithMany()
                        .HasForeignKey("TestDocumentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TestDocumentService.Models.DefinitionAndAbbrevation", b =>
                {
                    b.HasOne("TestDocumentService.Models.TestDocument", "TestDocument")
                        .WithMany("DefinitionAndAbbrevations")
                        .HasForeignKey("TestDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestDocument");
                });

            modelBuilder.Entity("TestDocumentService.Models.Participant", b =>
                {
                    b.HasOne("TestDocumentService.Models.Firm", "Firm")
                        .WithMany("Participants")
                        .HasForeignKey("FirmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firm");
                });

            modelBuilder.Entity("TestDocumentService.Models.Punch", b =>
                {
                    b.HasOne("TestDocumentService.Models.TestDocument", "TestDocument")
                        .WithMany("Punches")
                        .HasForeignKey("TestDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestDocumentService.Models.Test", "Test")
                        .WithMany("Punches")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");

                    b.Navigation("TestDocument");
                });

            modelBuilder.Entity("TestDocumentService.Models.Revision", b =>
                {
                    b.HasOne("TestDocumentService.Models.TestDocument", "TestDocument")
                        .WithMany("Revisions")
                        .HasForeignKey("TestDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestDocument");
                });

            modelBuilder.Entity("TestDocumentService.Models.Test", b =>
                {
                    b.HasOne("TestDocumentService.Models.TestDocument", "TestDocument")
                        .WithMany("Tests")
                        .HasForeignKey("TestDocumentId");

                    b.Navigation("TestDocument");
                });

            modelBuilder.Entity("TestDocumentService.Models.Firm", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("TestDocumentService.Models.Test", b =>
                {
                    b.Navigation("Punches");
                });

            modelBuilder.Entity("TestDocumentService.Models.TestDocument", b =>
                {
                    b.Navigation("DefinitionAndAbbrevations");

                    b.Navigation("Punches");

                    b.Navigation("Revisions");

                    b.Navigation("Tests");
                });
#pragma warning restore 612, 618
        }
    }
}
